files:
  - source: /two.csv
    translation: /folder/%language%
    multilingual_spreadsheet: 1
    scheme: 'identifier,context,source_phrase,fr,de,uk'
  - source: /all_translations.csv
    translation: /foldertin/%two_letters_code%
    multilingual_spreadsheet: 1
    first_line_contains_header: 1
    scheme: 'identifier,context,source_phrase,fr,de,uk'
