files:
  - source: /all_translations.csv
    translation: /papka/%two_letters_code%
    multilingual_spreadsheet: 1
    scheme: 'identifier,context,source_phrase,fr,de,uk'
  - source: /two.csv
    translation: /papka/%three_letters_code%
    scheme: 'identifier,context,source_phrase,fr'
