files:
  - source: /two.csv
    translation: /translation/%two_letters_code%
    scheme: 'identifier,context,source_phrase,fr'
  - source: /all_translations.csv
    translation: /translation/%three_letters_code%
    scheme: 'identifier,context,source_phrase,fr,de,uk'
