"preserve_hierarchy": true

files:
  - source: /two.csv
    "dest": "/conf/**/%file_name%.properties"
    translation: /folder/%language%
      translation_replace:
     "two": "Three"
    multilingual_spreadsheet: 1
    scheme: 'identifier,context,source_phrase,fr,de,uk'
    "type": "properties"
  - source: /all_translations.csv
    "dest": "/conf/**/%file_name%.properties"
    translation: /foldertin/%two_letters_code%
       translation_replace:
     "all_": ""
    multilingual_spreadsheet: 1
    first_line_contains_header: 1
    scheme: 'identifier,context,source_phrase,fr,de,uk'
    "type": "properties"
    
