preserve_hierarchy: true

files:
  - source: /two.csv
    dest: "/conf/**/%file_name%.properties"
    translation: /translation/%two_letters_code% 
    translation_replace: 
      "two": "three"
    type: "properties"
    dest: "/conf/**/%file_name%.properties"
    scheme: 'identifier,context,source_phrase,fr'
  - source: /all_translations.csv
    dest: "/conf/**/%file_name%.properties"
    translation: /translation/%three_letters_code%
    translation_replace: 
      "all_": ""
    type: "properties"
    scheme: 'identifier,context,source_phrase,fr,de,uk'
